spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person_db?createDatabaseIfNotExist=true
    username: mysql
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8082