version: '3.1'

services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      POSTGRES_USERNAME: mysql
      POSTGRES_PASSWORD: root
      POSTGRES_DB: person_db

    volumes:
      - /var/lib/mysql/data